[build]
  command = "npm install && npm run build"
  publish = "client/dist"

[context.production.environment]
  NODE_VERSION = "nvm ls-remote"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200